version: 0.0
os: linux
files:
  - source: .
    destination: /home/ubuntu/test_app
hooks:
  BeforeInstall:
    - location: scripts/build
      timeout: 3000
      runas: root
    - location: scripts/start_server
      timeout: 300
      runas: root

